services:

  backend:
    build: ./Backend
    container_name: mern_backend
    restart: always
    ports:
      - "5000:4000"
    environment:
     - MONGO_URI=${MONGO_URI}

  frontend:
    build: ./Frontend
    container_name: mern_frontend
    restart: always
    ports:
      - "3000:80"
    environment:
     - VITE_BASE_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo-data: